### ISSUE TITLE
Error response from daemon: client is newer than server

### ISSUE THREAD

**Issue by webbj74** [anavarre/drucker#5]
```
$ docker --version
Docker version 1.12.0-rc4, build e4a0dbc, experimental

$ docker-machine --version
docker-machine version 0.8.0-rc2, build 4ca1b85

$ ansible --version
ansible 2.1.0.0
  config file =
  configured module search path = Default w/o overrides

$ drucker
Error response from daemon: client is newer than server (client API version: 1.24, server API version: 1.23)
Error response from daemon: client is newer than server (client API version: 1.24, server API version: 1.23)
Error response from daemon: client is newer than server (client API version: 1.24, server API version: 1.23)
Error response from daemon: client is newer than server (client API version: 1.24, server API version: 1.23)
Error response from daemon: client is newer than server (client API version: 1.24, server API version: 1.23)
Error response from daemon: client is newer than server (client API version: 1.24, server API version: 1.23)
Error response from daemon: client is newer than server (client API version: 1.24, server API version: 1.23)
Error response from daemon: client is newer than server (client API version: 1.24, server API version: 1.23)
Error response from daemon: client is newer than server (client API version: 1.24, server API version: 1.23)
Error response from daemon: client is newer than server (client API version: 1.24, server API version: 1.23)
Error response from daemon: client is newer than server (client API version: 1.24, server API version: 1.23)
Error response from daemon: client is newer than server (client API version: 1.24, server API version: 1.23)
```

**Comment by anavarre** [comment]
Sorry for the response lag. I'm currently OOO with mobile only. Will expand by EOW. 

This error seems to be unrelated to drucker and instead originating from docker-machine. Does `docker ps - a` works for you? If not, then it's indeed something acting up with the MacOS docker setup.

**Comment by anavarre** [comment]
Back to my laptop, I researched that issue more but cannot test any of the suggested solutions as I don't have a Mac. The gist seems to be:

> Docker is implemented as a client/server. The client is the docker CLI, and the server is ran using "docker daemon" (previously -D). The client and the server communicates using an http API. This API is versionned, and some versions have BC breaks. The reason for this error is often when you talk to a remote daemon, for example if you are under OSX and use docker-machine or boot2docker. If that's the case, you,'ll have to ensure both the clients and the server run a compatible version.

Looks like leveraging [DOCKER_API_VERSION](https://docs.docker.com/engine/reference/commandline/cli/#environment-variables) could be helpful here.

Also, here are the most relevant links I could come across:
- https://getcarina.com/blog/docker-version-manager/
- https://forums.docker.com/t/mismatch-between-api-versions-after-automatic-update-to-1-11-0-beta6-with-docker-machine-on-amazon/8549/10
- http://stackoverflow.com/questions/34015271/error-response-from-daemon-client-is-newer-than-server
- https://forums.docker.com/t/docker-for-mac-stopped-running-docker-related-commands/16153/4

**Comment by anavarre** [comment]
Closing. Please re-open if you need more assistance.
